from enum import StrEnum
"""Constants for the Victron VE.Direct integration."""


DOMAIN = "victron_vedirect"

CONF_DEVICE_TYPE = "device_type"


class VictronDeviceType(StrEnum):
    BMV_60X = "BMV_60X"
    BMV_70X = "BMV_70X"
    BMV_71X_SMARTSHUNT = "BMV_71X_SMARTSHUNT"
    MPPT = "MPPT"
    PHOENIX_INVERTER = "PHOENIX_INVERTER"
    PHOENIX_CHARGER = "PHOENIX_CHARGER"
    SMART_BUCKBOOST = "SMART_BUCKBOOST"


class VEDirectKeys(StrEnum):
    V = "V"
    V2 = "V2"
    V3 = "V3"
    VS = "VS"
    VM = "VM"
    DM = "DM"
    VPV = "VPV"
    PPV = "PPV"
    I = "I"
    I2 = "I2"
    I3 = "I3"
    IL = "IL"
    LOAD = "LOAD"
    T = "T"
    P = "P"
    CE = "CE"
    SOC = "SOC"
    TTG = "TTG"
    ALARM = "Alarm"
    RELAY = "Relay"
    AR = "AR"
    OR = "OR"
    H1 = "H1"
    H2 = "H2"
    H3 = "H3"
    H4 = "H4"
    H5 = "H5"
    H6 = "H6"
    H7 = "H7"
    H8 = "H8"
    H9 = "H9"
    H10 = "H10"
    H11 = "H11"
    H12 = "H12"
    H13 = "H13"
    H14 = "H14"
    H15 = "H15"
    H16 = "H16"
    H17 = "H17"
    H18 = "H18"
    H19 = "H19"
    H20 = "H20"
    H21 = "H21"
    H22 = "H22"
    H23 = "H23"
    ERR = "ERR"
    CS = "CS"
    BMV = "BMV"
    FW = "FW"
    FWE = "FWE"
    PID = "PID"
    SERIAL = "SER#"
    HSDS = "HSDS"
    MODE = "MODE"
    AC_OUT_V = "AC_OUT_V"
    AC_OUT_I = "AC_OUT_I"
    AC_OUT_S = "AC_OUT_S"
    WARN = "WARN"
    MPPT = "MPPT"
    MON = "MON"
    DC_IN_V = "DC_IN_V"
    DC_IN_I = "DC_IN_I"
    DC_IN_P = "DC_IN_P"
